load("//build_defs/codegen/cc:script_header.bzl", "script_carrier")

script_carrier(
    name = "test",
    out = ":test.h",
    header_guard = "TEST_H_",
    lua = "test.lua",
    symbol = "program",
)
