load("@rules_go//go:def.bzl", "go_binary")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

go_binary(
    name = "header_gen",
    srcs = [
        "header_gen.go",
    ],
    pure = "on",
)
