cc_binary(
    name = "single_script",
    srcs = [
        "single_script.c",
    ],
    deps = [
        "@lua_mainline//src:core",
        "@lua_mainline//src:includes",
        "@lua_mainline//src:libraries",
    ],
)
